---
- name: Setup WireGuard VPN on Ubuntu (with firewalld)
  hosts: ubuntu_arm
  become: true

  vars:
    wg_interface: wg0
    wg_port: 16390
    wg_private_key: "{{ lookup('file', 'privatekey') }}"
    wg_address: "10.0.0.1/24"

  tasks:
    - name: Install required packages
      apt:
        name:
          - wireguard
        state: present
        update_cache: yes

    - name: Ensure /etc/wireguard exists
      file:
        path: /etc/wireguard
        state: directory
        mode: '0700'

    - name: Generate WireGuard config
      copy:
        dest: "/etc/wireguard/{{ wg_interface }}.conf"
        content: |
          [Interface]
          PrivateKey = {{ wg_private_key }}
          Address = {{ wg_address }}
          ListenPort = {{ wg_port }}
          SaveConfig = true
        owner: root
        group: root
        mode: '0600'

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Open UDP port for WireGuard
      firewalld:
        port: "{{ wg_port }}/udp"
        permanent: true
        immediate: true
        state: enabled


    - name: Reload firewalld rules
      command: firewall-cmd --reload


    - name: Start and enable WireGuard service
      systemd:
        name: "wg-quick@{{ wg_interface }}"
        enabled: true
        state: started
