---
- name: Install Docker and Docker Compose V2 on Ubuntu ARM VMs (Best Practice)
  hosts: ubuntu_arm
  become: true

  vars:
    docker_apt_url: "https://download.docker.com/linux/ubuntu"

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: "{{ docker_apt_url }}/gpg"
        state: present
        validate_certs: true

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=arm64] {{ docker_apt_url }} {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker Engine and Compose V2
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add current user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Check Docker Compose V2 version
      ansible.builtin.command: docker compose version
      register: compose_version
      changed_when: false

    - name: Show Docker Compose V2 version
      ansible.builtin.debug:
        msg: "Installed Docker Compose version: {{ compose_version.stdout }}"
