---
- name: Setup and Secure Basic Environment on Ubuntu ARM VMs with UFW + fail2ban
  hosts: ubuntu_arm
  become: yes

  vars:
    timezone: Asia/Taipei
    ntp_servers:
      - time.google.com
      - time1.google.com
      - time2.google.com
      - time3.google.com

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install basic packages
      apt:
        name:
          - git
          - wget
          - iputils-ping
          - vim
          - curl
          - htop
          - fail2ban
          - ufw
          - chrony
          - unzip
          - iperf3
          - lsof
          - net-tools
          - bind9-utils
        state: present

    - name: Set system timezone
      community.general.timezone:
        name: "{{ timezone }}"

    - name: Configure Google NTP servers
      blockinfile:
        path: /etc/chrony/chrony.conf
        marker: "# {mark} GOOGLE NTP CONFIG"
        block: |
          {% for server in ntp_servers %}
          server {{ server }} iburst
          {% endfor %}
      notify:
        - Restart chrony

    - name: Ensure chrony service is running and enabled
      service:
        name: chrony
        state: started
        enabled: yes

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow UDP port 16390 for WireGuard VPN
      ufw:
        rule: allow
        port: "16390"
        proto: udp

    - name: Enable UFW (Uncomplicated Firewall)
      ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Ensure fail2ban service is running and enabled
      service:
        name: fail2ban
        state: started
        enabled: yes

    - name: Configure fail2ban for SSH
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [sshd]
          enabled = true
          port    = ssh
          logpath = %(sshd_log)s
          backend = systemd
          maxretry = 5
          bantime = 3600
          findtime = 600

      notify:
        - Restart fail2ban

  handlers:
    - name: Restart chrony
      service:
        name: chrony
        state: restarted

    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted
